services:
    vapor:
        build:
            context: /home/ubuntu/laravel
            dockerfile: Dockerfile
        ports:
            - published: 8080
              target: 8080
        restart: always
